# Generated by Django 4.2.30 on 2026-09-12 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneRuleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("version", models.PositiveIntegerField()),
                ("target_column", models.CharField(max_length=255)),
                ("default_region", models.CharField(default="AU", max_length=2)),
                ("target_format", models.CharField(default="E164", max_length=16)),
                ("preserve_invalid", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-version"],
            },
        ),
        migrations.CreateModel(
            name="RuleGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("next_version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="RuleExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_file_id", models.UUIDField()),
                ("output_file_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("changed_rows", models.PositiveIntegerField(null=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("finished_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                (
                    "rule_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rules.phoneruleversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="phoneruleversion",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rules.rulegroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="phoneruleversion",
            constraint=models.UniqueConstraint(
                fields=("group", "version"), name="unique_phone_rule_version"
            ),
        ),
    ]
